
services:
  backend:
    container_name: artisan-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - .:/app
